### ISSUE TITLE
Labeling of "Full view" resources

### ISSUE THREAD

**Issue by akhtars** [ExLibrisGroup/alma-hathitrust-availability#3]
Hello, thank you for making this app available to the Alma community. I am noticing that the availability status for full-view items is not appearing as expected in the Alma app view. For example, _Paradise and the Peri_, (OCoLC)ocm04476808, is fully available via HathiTrust, and the [HT Bib API data](https://catalog.hathitrust.org/api/volumes/brief/oclc/4476808.json) returns `usRightsString: "Full view"`. However, the cloud app [seems to be expecting](https://github.com/ExLibrisGroup/alma-hathitrust-availability/blob/e30b44d005c509a47068376e6437b5010301f477/cloudapp/src/app/hathitrust.ts#L49) "view" to be capitalized, so in Alma it shows availability as "Limited" instead. The [HT API documentation](https://www.hathitrust.org/bib_api#basicjson) might be mistaken in describing the expected value as "Full View". I am not sure if this is consistent across the HT dataset.

![HT-availability-limited](https://user-images.githubusercontent.com/3810132/87989824-bc464c80-cab0-11ea-9a4e-2eea74f27b92.PNG)

**Comment by jweisman** [comment]
Thanks for reporting this! We've pushed a new version which should fix it. It would be great if you could check it again.

**Comment by akhtars** [comment]
This is working as expected for titles with full-view items. Thanks for the quick fix!
