### ISSUE TITLE
App is stuck loading

### ISSUE THREAD

**Issue by saclaudi** [ExLibrisGroup/alma-hathitrust-availability#5]
Hello,

We have one librarian attempting to use this and on their end the app just keeps spinning. They have tried both Chrome and Firefox and have had no luck. We have also asked them to uninstall and reinstall the app but the issue persists.
![8-5-20 ht app error](https://user-images.githubusercontent.com/40008115/90289057-ea107e00-de2f-11ea-9f11-ecdeac6c1920.jpg)

**Comment by jweisman** [comment]
Hi @saclaudi . Thanks for your question. I exported this record from your environment and imported it into mine. Then I ran the HathiTrust app and got back a link to the record:

<img width="1297" alt="Screen Shot 2020-08-16 at 9 47 13 " src="https://user-images.githubusercontent.com/80420/90328520-9d4eb380-dfa5-11ea-9abc-d03086a15ba7.png">

If you're using Chrome, can you try opening View-->Developer-->JavaScript Console from the menu and copy what appears there when the spinner is showing?

Thanks!

**Comment by saclaudi** [comment]
Hi @jweisman. Thanks for the reply, I do want to note that this issue was only reported by one user. Below is the screenshot of their console logs:
![81920AlmaHTappconsoletab](https://user-images.githubusercontent.com/40008115/90684389-f411f280-e21c-11ea-8d0a-849bb763f1c9.jpg)

Thanks

**Comment by jweisman** [comment]
Thanks for your reply. We've updated the app to include more error messages. If you could ask the librarian to try again and take a screenshot if a red error message pops up. Thanks!

**Comment by saclaudi** [comment]
Hello Josh,

The librarian confirmed they saw an error popup and this is the screenshot of their console log.
![Alma HT APP Annotation 2020-08-25 160008](https://user-images.githubusercontent.com/40008115/91319734-911ae100-e771-11ea-86ef-9c83f9a0bcf4.jpg)

Thanks

**Comment by jweisman** [comment]
Thanks for the update. Looks like we'll need to try to arrange a screen-sharing session to see what's happening for this user. Can you email me or [direct message me on Twitter ](https://twitter.com/joshmweisman) and we can set something up.

**Comment by saclaudi** [comment]
Hello Josh,

What email can you be reached at?

**Comment by jweisman** [comment]
Hi @saclaudi - Thanks for the session yesterday. It looks like there is an issue with the roles for the Get BIB API. We will add additional privileges in December (like Physical Inventory Operator). Until that's done, if you add the Cataloger role to the user she should be able to use the app.

Thanks.
